### ISSUE TITLE
Incorrect indentation if spaces/tabs of first line are not copied

### ISSUE THREAD

**Issue by dannypernik** [lesgrieve/paste-indent#4]
If highlight is started from first character of indented line:
![Screenshot 2023-11-27 at 5 00 37 PM](https://github.com/lesgrieve/paste-indent/assets/3347095/5600e074-6f67-45be-a122-a47e767c1ca0)
![Screenshot 2023-11-27 at 5 01 02 PM](https://github.com/lesgrieve/paste-indent/assets/3347095/5f3b4f36-6122-48c8-a83f-9a0e6ff15f3d)

If highlight is started from column 1 of indented line:
![Screenshot 2023-11-27 at 5 01 28 PM](https://github.com/lesgrieve/paste-indent/assets/3347095/e3222d6e-4081-4be0-9b68-a7507a6f0e2b)
![Screenshot 2023-11-27 at 5 01 39 PM](https://github.com/lesgrieve/paste-indent/assets/3347095/e90aa8be-0337-4496-9363-1fd94a45436f)

I believe this can be fixed by identifying the column number of the first character copied and prepending that number of spaces (or tabs = column number / tab size if the file uses tabs?)

**Comment by lesgrieve** [comment]
I can reproduce your problem. I guess I didn't see it before because I select lines when indentation is desired and use normal paste otherwise. Your suggestion should work. Please give me some time to implement the fix.

**Comment by gilbertohasnofb** [comment]
Just came to report this same issue, thanks for taking a look at it.

One potential scenario is that might be worth thinking about is when copying from the middle of a line that has indentation; in that case, I think the indentation of the line should still be considered when pasting. E.g.:

* copying a selection with multiple lines starting from the middle of an indented line:
![image](https://github.com/lesgrieve/paste-indent/assets/5700795/91f60302-0f15-4b51-a62d-63bb40345efc)

* and pasting it:
![image](https://github.com/lesgrieve/paste-indent/assets/5700795/466696bb-f8e4-4193-81b8-828947979a03)

* should result in this:
![image](https://github.com/lesgrieve/paste-indent/assets/5700795/3d2e9e28-800b-49bf-a4d9-7da75378f0df)

**Comment by lesgrieve** [comment]
@dannypernik, I spent a little time looking into this. The intractable problem is that at the time of pasting, when the extension is invoked, there is no way of telling the column of the first character of the selection, all the extension knows is that the clipboard contains
```
<div>
          <p>
            <ul>
              <li>
                Item 1
              </li>
              <li>
                Item 2
              </li>
            </ul>
          </p>
        </div>
```
The text block may have been copied from anywhere; webpage, terminal, or other editor. I specifically avoid reformatting text in paste-indent since I want it to keep the indentation of the selection. I totally get your use case, maybe you are selecting everything between matching tags.

I propose three possible approaches to your problem:
1. Select the whole beginning line
    I have a keybindings.json with
    ```
    {
        "key": "ctrl+cmd+l",
        "command": "expandLineSelection",
        "when": "textInputFocus"
    },
    ```
    to select the whole line with Super+Ctrl+L. For your case, I would select what you have selected, triggered expandLineSelection, then copy.

2. Use normal paste
    In your specific example, the outcome would have been good if you used normal paste. My keybindings.json has
    ```
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction"
    },
    {
        "key": "ctrl+cmd+v",
        "command": "extension.paste-indent"
    },
    ```
    so I use normal editor.action.clipboardPasteAction by default and extension.paste-indent only when I want to preserve indentation. This was the pattern used in SublimeText3.

3. Play with reformatting
    There are a few commands like editor.action.formatChanges, editor.action.formatSelection.multiple, or editor.action.formatDocument.none which you can trigger with a key that can fix your indentation after pasting.

I am on macOS so your key mappings may vary. My keybindings are in "~/Library/Application Support/Code/User/keybindings.json".

@gilbertohasnofb, your example is similar. The outcome
```
    def foo(arg):
        pass

    def bar(arg):
            pass
```
is undesired since the clipboard contains only
```
(arg):
        pass
```
I would use approach 2 or 3 in your case. I am open to ideas but cannot determine the cursor position at the time of copy.

**Comment by dannypernik** [comment]
@lesgrieve thank you for your detailed assessment. One of these options should work for me.

**Comment by SimonEast** [comment]
It's a bit frustrating that this cannot work the same way as Sublime Text. Unfortunately method 2 (using normal paste) only works if you're pasting into the same indentation level as where you copied from.

But I understand that you can only work with what's on the clipboard. Well, unless you hooked into the copy command too? Not sure if that's a possibility? 

I'm pretty sure that is what Sublime does. And that is based on a couple of tests I just ran where it appears that copying text _from another program_ and pasting into Sublime exhibits the same issue we're seeing above, but if you do the copy _within Sublime_, the pasted text indents beautifully, even at a different level of indentation.
