### ISSUE TITLE
Can't Paste into Search Box

### ISSUE THREAD

**Issue by snappa-app** [lesgrieve/paste-indent#5]
Steps to reproduce:

- Bind `paste-indent` command to `CMD-v`
- Go into a text file, and copy text you would like to search for
- Press `CMD-f` to focus on the file search box
- Press `CMD-v` to paste-indent

Result: Pastes into the file instead of the search box. This should paste the text into the search box because focus is on that input.

Great plugin btw - default VSCode paste is rough.

**Comment by lesgrieve** [comment]
I am impressed that you are using paste-indent as your primary paste action, my habit from Sublime Text 3 days was to have Ctrl+V paste and Ctrl+Shift+V paste with indentation.
That said, I may have a solution to your problem. Map Cmd+V to paste indent when the text editor has focus and have it trigger normal paste when text editor does not have focus. More information about keybinding conditions is available on https://code.visualstudio.com/api/references/when-clause-contexts. You may be able to improve my solution by using a different context key (https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys). Try updating ~/Library/Application Support/Code/User/keybindings.json with:
```
    {
        "key": "cmd+v",
        "command": "extension.paste-indent",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "!editorTextFocus"
    },
```
